server:
  port: 8081

spring:
  application:
    name: grain-app-auth
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  main:
    allow-bean-definition-overriding: true

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: GrainAppSimple
  ssl-required: external
  resource: grain-manager
  verify-token-audience: true
  credentials:
    secret: 88f9c5cb-35de-4dba-8c16-799f4ef6a8de
  confidential-port: 0
  policy-enforcer: {}

client-manager:
  id: grain-manager
  secret: 712285b5-d234-4658-af16-89335f2bb364
